name: quetz-client
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - make
  - numpydoc
  - pip
  - pre-commit
  - pytest>=6 # Adds --import-mode option
  - pytest-cov
  - sphinx
  - sphinxcontrib-apidoc
  - sphinx_rtd_theme
  - quetz >=0.4.0
  - pytest-mock
  - requests-mock
  - httpx
  - fire
  - tbump
  - pip:
      - git+https://github.com/jupyter-server/jupyter_releaser.git@v2
