name: quetz-client
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - make
  - numpydoc
  - pip
  - pre-commit
  - pytest>=6 # Adds --import-mode option
  - pytest-cov
  - setuptools_scm
  - sphinx
  - sphinxcontrib-apidoc
  - sphinx_rtd_theme
  - sqlalchemy<2.0.0
  - quetz >=0.4.0
  - pytest-mock
  - requests-mock
  - httpx
  - fire
  - dacite
